import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
// const stories = [
//   {
//     id: 1,
//     title: 'How 7 lines code turned into $36 Billion Empire',
//     category: 'BUSINESS',
//     date: '27 Sep 2022',
//     status: 'published',
//     image: 'https://nexacu.com.au/media/odahyq3q/a-beginner-s-guide-to-python-programming-complete-guide.jpg',
//   },
//   {
//     id: 2,
//     title: 'Chez pierre restaurant in Monte Carlo by Vudafieri',
//     category: 'BUSINESS',
//     date: '20 Sep 2022',
//     status: 'Created',
//     image: 'https://evolvemga.com/wp-content/uploads/2017/02/Corporate-Buildings.jpg',
//   },
//   {
//     id: 3,
//     title: 'Teknion wins Gold at 2022 International Design Awards',
//     category: 'Fashion',
//     date: '20 Sep 2022',
//     status: 'draft',
//     image: 'https://c.stocksy.com/a/hhkI00/z9/4469437.jpg',
//   },
//   {
//     id: 4,
//     title: 'How 7 lines code turned into $36 Billion Empire',
//     category: 'BUSINESS',
//     date: '20 Sep 2022',
//     status: 'published',
//     image: 'https://nexacu.com.au/media/odahyq3q/a-beginner-s-guide-to-python-programming-complete-guide.jpg',
//   },
//   {
//     id: 5,
//     title: 'How 7 lines code turned into $36 Billion Empire',
//     category: 'BUSINESS',
//     date: '27 Sep 2022',
//     status: 'published',
//     image: 'https://nexacu.com.au/media/odahyq3q/a-beginner-s-guide-to-python-programming-complete-guide.jpg',
//   },
//   {
//     id: 6,
//     title: 'Chez pierre restaurant in Monte Carlo by Vudafieri',
//     category: 'BUSINESS',
//     date: '20 Sep 2022',
//     status: 'Created',
//     image: 'https://evolvemga.com/wp-content/uploads/2017/02/Corporate-Buildings.jpg',
//   },
//   {
//     id: 7,
//     title: 'Teknion wins Gold at 2022 International Design Awards',
//     category: 'Fashion',
//     date: '20 Sep 2022',
//     status: 'published',
//     image: 'https://c.stocksy.com/a/hhkI00/z9/4469437.jpg',
//   },
//   {
//     id: 8,
//     title: 'How 7 lines code turned into $36 Billion Empire',
//     category: 'BUSINESS',
//     date: '20 Sep 2022',
//     status: 'published',
//     image: 'https://nexacu.com.au/media/odahyq3q/a-beginner-s-guide-to-python-programming-complete-guide.jpg',
//   },
// ];